[id="openshift-pipelines_{context}"]
= OpenShift Pipelines

[IMPORTANT]
====
Just a test site
====

OpenShift Pipelines are cloud-native, continuous integration and delivery solutions based on Kubernetes resources. It uses link:https://tekton.dev[Tekton] Pipelines to automate deployments across multiple platforms by abstracting away the underlying details. Tekton introduces a number of standard link:https://kubernetes.io/docs/concepts/extend-kubernetes/api-extension/custom-resources/[Custom Resource Definitions (CRDs)] for defining pipelines that are portable across Kubernetes distributions.

* OpenShift Pipelines are designed for microservices and decentralized teams.
* OpenShift Pipelines uses standard CI/CD pipeline definitions that are easy to extend and integrate with existing Kubernetes tools, enabling you to scale on-demand.
* You can use them to build images with Kubernetes tools such as Source-to-Image (S2I), Buildah, Buildpacks, and Kaniko and are portable across any Kubernetes platform.
* You can use the OpenShift Developer Console to create Tekton resources, view logs of pipeline runs, and manage pipelines under OpenShift project namespaces.


== Additional resources

* For more details on defining pipelines, see the link:https://openshift.github.io/pipelines-docs/docs/docs/assembly_using-pipelines.html[Using Pipelines documentation].
* For more information on Tekton see the link:https://github.com/tektoncd[Tekton Pipelines documentation].
* Visit our link:https://github.com/openshift/pipelines-docs[GitHub] repository for more information or to contribute.

